name: TeamWars
main: circus.teamwars.PluginManager
version: ${project.version}
api-version: 1.17
permissions:
  teamwars.manage:
    description: Permission to setup teams
    default: op
commands:
  addteams:
    description: Create new teams
    usage: /addteams <team name 1> <color 1> <team name 2> <color 2> ...
    permission: teamwars.manage
  remteams:
    description: Delete teams
    usage: /remteams <team name 1> <team name 2> ...
    permission: teamwars.manage
  addmembers:
    description: Add players to a team
    usage: /addmembers <team name> <player 1> <player 2> ...
    permission: teamwars.manage
  remmembers:
    description: Remove players from a team
    usage: /remmembers <team name> <player 1> <player 2> ...
    permission: teamwars.manage
  setstate:
    description: Set game state
    usage: /setstate <INACTIVE|PREPARATION|PVP|NOPVP>
    permission: teamwars.manage
  setlives:
    description: Set players' lives
    usage: /setlives <player 1> <lives 1> <player 2> <lives 2> ...
    permission: teamwars.manage
  startgame:
    description: Start game
    usage: /startgame <time until PVP>
    permission: teamwars.manage
